# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

minio:
  service: S3
  endpoint: 'http://localhost:9000'
  force_path_style: true
  access_key_id: <%= ENV['MINIO_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['MINIO_SECRET_KEY'] %>
  region: minio
  bucket: qna-dev
